### ISSUE TITLE
characteristic_sections of Running Path Schema should contain named attributes

### ISSUE THREAD

**Issue by apriljunge** [railtoolkit/schema#4]
Currently, `characteristic_sections ` is defined as an array whose property is defined by the order.
I think it would be better and more future-proof to use named properties.

Like:
```yaml
characteristic_sections:
  - position: 0
    speed: 10
    resistance: 0
  - position: 0
    speed: 10
    resistance: 0
```

The same does apply to `points_of_interest`

**Comment by apriljunge** [comment]
Maybe then `characteristic_sections` and `points_of_interest` could be unified?

**Comment by kaat0** [comment]
Agree on naming the properties!

`characteristic_sections` and `points_of_interest` are different in nature and properties. One of the reason of the existence of this schema is that it can be written manually. Since both come from different sources, it is easier not to merge them in the `path`-file but in the program using the `path`-file. Therefore, my current position is not to unify them.

**Comment by kaat0** [comment]
```YAML
points_of_interest:
  - position: 2000.00
    label: main_signal_1
    measure: front
  - position: 9050.00
    label: clearing_point_1
    measure: rear
```
